### ISSUE TITLE
Word to PDF conversion issues

### ISSUE THREAD

**Issue by aayu-ramola** [PHPOffice/PHPWord#1023]
Hello,
I am using PHPWord with Cakephp 1.3. I used TCPDF, DomPDF, and MPDF to convert a Resume/CV docx to PDF but the output file is not as expected. On page 2 onwards, it contains a lot of extra spaces, a single word is broken into multiple lines, and images (e.g. logo ) is not coming (pls see attachment). Any tips on getting this to work? Thanks

Below is the code I wrote: 

Using MPDF:
    App::import('Vendor', 'doctopdf/vendor/autoload');
    \PhpOffice\PhpWord\Settings::setPdfRendererPath(APP.'vendors'.DS.'mpdf'.DS.'mpdf.php');
    \PhpOffice\PhpWord\Settings::setPdfRendererName('MPDF');
    $phpWord = \PhpOffice\PhpWord\IOFactory::load($docPath);
    $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'PDF');
    $objWriter->save($PdfPath,true);

Using TCPDF:
    App::import('Vendor', 'doctopdf/vendor/autoload');
    \PhpOffice\PhpWord\Settings::setPdfRendererPath(APP.'vendors'.DS.tcpdf'.DS.'tcpdf.php');
    \PhpOffice\PhpWord\Settings::setPdfRendererName('TCPDF');
    $phpWord = \PhpOffice\PhpWord\IOFactory::load($docPath);
    $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'PDF');
    $objWriter->save($PdfPath,true);

Using DomPDF I am getting error : 
Fatal error: Uncaught exception 'DOMPDF_Exception' with message 'An input file is required (i.e. input_file _GET variable).' in C:\xampp\htdocs\recruiter\app\vendors\dompdf\dompdf.php:199 Stack trace: #0 C:\xampp\htdocs\recruiter\app\vendors\doctopdf\vendor\phpoffice\phpword\src\PhpWord\Writer\PDF\AbstractRenderer.php(89): require_once() #1 C:\xampp\htdocs\recruiter\app\vendors\doctopdf\vendor\phpoffice\phpword\src\PhpWord\Writer\PDF.php(61): PhpOffice\PhpWord\Writer\PDF\AbstractRenderer->__construct(Object(PhpOffice\PhpWord\PhpWord)) #2 C:\xampp\htdocs\recruiter\app\vendors\doctopdf\vendor\phpoffice\phpword\src\PhpWord\IOFactory.php(44): PhpOffice\PhpWord\Writer\PDF->__construct(Object(PhpOffice\PhpWord\PhpWord)) #3 C:\xampp\htdocs\recruiter\app\controllers\candidates.php(9755): PhpOffice\PhpWord\IOFactory::createWriter(Object(PhpOffice\PhpWord\PhpWord), 'PDF') #4 C:\xampp\htdocs\recruiter\app\controllers\candidates.php(8590): CandidatesController->convertDocToPdf('C:\\xampp\\ht in C:\xampp\htdocs\recruiter\app\vendors\dompdf\dompdf.php on line 199

Attachment: [Alok_Kumar.pdf](https://github.com/PHPOffice/PHPWord/files/849722/Alok_Kumar.pdf)

**Comment by levieraf** [comment]
I have the same problem!

**Comment by levieraf** [comment]
To convert .docx to pdf I am checking the command line doc2pdf, I did the test with this and work ok! also I did a test using the soffice of libreoffice which mean that you need to install the libreoffice. Bc I cannot see a librery on php or python or ruby that convert correctly a docx to pdf.

**Comment by tantos** [comment]
I got the same problem.
I lost the header and styles when converting word to pdf using MPDF, TCPDF or DomPDF.

**Comment by yjrowe** [comment]
I also have the problem.
I got random code and the img became big when converting docx word to pdf using DomPDF.
the problem is so egg pain.

**Comment by moly4565** [comment]
I got same problem.
I lost header footer,radio button when converting word to pdf. pls help me.
my code below
define('PHPWORD_BASE_DIR', realpath(__DIR__));
require 'phpoffice/phpword/vendor/autoload.php';
require 'phpoffice/phpword/vendor/tecnickcom/tcpdf/tcpdf.php';

$PdfPath = realpath(__DIR__).'/phpoffice/phpword/vendor/tecnickcom/tcpdf';
\PhpOffice\PhpWord\Settings::setPdfRendererPath($PdfPath);
\PhpOffice\PhpWord\Settings::setPdfRendererName('TCPDF');
//echo $paths=realpath(__DIR__).'/'.$fpdf1;
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->SetCreator(PDF_CREATOR);
$pdf->AddPage();
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
$pdf->setPrintHeader(true);
$pdf->setPrintFooter(true);

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
// set auto page breaks
 $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
 
// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
$pdf = \PhpOffice\PhpWord\IOFactory::load(realpath(__DIR__).'/'.$file);

$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($pdf ,'PDF');
$xmlWriter->save('pdf/'.substr($file,5,-5).'.pdf');

**Comment by yjrowe** [comment]
I can not solve this problem with php,I just used python.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"moly4565"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 晚上6:24
收件人:&nbsp;"PHPOffice/PHPWord"<PHPWord@noreply.github.com&gt;;
抄送:&nbsp;"罗永均"<417969832@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PHPOffice/PHPWord] Word to PDF conversion issues (#1023)




I got same problem.
 I lost header footer,radio button when converting word to pdf. pls help me.
 my code below
 define('PHPWORD_BASE_DIR', realpath(DIR));
 require 'phpoffice/phpword/vendor/autoload.php';
 require 'phpoffice/phpword/vendor/tecnickcom/tcpdf/tcpdf.php';
 
$PdfPath = realpath(DIR).'/phpoffice/phpword/vendor/tecnickcom/tcpdf';
 \PhpOffice\PhpWord\Settings::setPdfRendererPath($PdfPath);
 \PhpOffice\PhpWord\Settings::setPdfRendererName('TCPDF');
 //echo $paths=realpath(DIR).'/'.$fpdf1;
 $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
 $pdf-&gt;SetCreator(PDF_CREATOR);
 $pdf-&gt;AddPage();
 $pdf-&gt;SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
 // set header and footer fonts
 $pdf-&gt;setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
 $pdf-&gt;setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
 $pdf-&gt;setPrintHeader(true);
 $pdf-&gt;setPrintFooter(true);
 
// set default monospaced font
 $pdf-&gt;SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
 // set margins
 $pdf-&gt;SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
 $pdf-&gt;SetHeaderMargin(PDF_MARGIN_HEADER);
 $pdf-&gt;SetFooterMargin(PDF_MARGIN_FOOTER);
 $pdf-&gt;SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
 $pdf-&gt;SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
 // set auto page breaks
 $pdf-&gt;SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
 
// set image scale factor
 $pdf-&gt;setImageScale(PDF_IMAGE_SCALE_RATIO);
 $pdf = \PhpOffice\PhpWord\IOFactory::load(realpath(DIR).'/'.$file);
 
$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($pdf ,'PDF');
 $xmlWriter-&gt;save('pdf/'.substr($file,5,-5).'.pdf');

**Comment by yvescleuder** [comment]
I problem.. not converting header..

**Comment by mpolch** [comment]
I am having problems with tabulators. They are just moved to the left..

**Comment by Asmitta-01** [comment]
> I am having problems with tabulators. They are just moved to the left..

I have the same problem.

**Comment by Asmitta-01** [comment]
Anyone has a tip for it please ?
