### ISSUE TITLE
Error: Invalid style value: chosung Options:bullet,decimal,upperRoman,lowerRoman,upperLetter,lowerLetter'

### ISSUE THREAD

**Issue by Global90** [PHPOffice/PHPWord#1119]
Code:
```
public static function GetDocxContent($path)
    {
        $phpWord = \PhpOffice\PhpWord\IOFactory::load($path);

        //$phpWord->save('dfdf.htm','HTML');die;
        $text = '';
        $sections = $phpWord->getSections();
        foreach ($sections as $key => $value) {
            $sectionElement = $value->getElements();
            foreach ($sectionElement as $elementKey => $elementValue) {
                if ($elementValue instanceof \PhpOffice\PhpWord\Element\TextRun) {
                    $secondSectionElement = $elementValue->getElements();
                    foreach ($secondSectionElement as $secondSectionElementKey => $secondSectionElementValue) {
                        if ($secondSectionElementValue instanceof \PhpOffice\PhpWord\Element\Text) {

                            $text .= $secondSectionElementValue->getText();
                        }
                    }
                }
            }
        }

        return $text;
    }
```

Error:
```
Exception 'InvalidArgumentException' with message 'Invalid style value: chosung Options:bullet,decimal,upperRoman,lowerRoman,upperLetter,lowerLetter'

in /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Style/AbstractStyle.php:289

Stack trace:
#0 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Style/NumberingLevel.php(189): PhpOffice\PhpWord\Style\AbstractStyle->setEnumVal('chosung', Array, NULL)
#1 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Style/AbstractStyle.php(166): PhpOffice\PhpWord\Style\NumberingLevel->setFormat('chosung')
#2 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Style/AbstractStyle.php(181): PhpOffice\PhpWord\Style\AbstractStyle->setStyleValue('format', 'chosung')
#3 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Style/Numbering.php(122): PhpOffice\PhpWord\Style\AbstractStyle->setStyleByArray(Array)
#4 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Style/AbstractStyle.php(166): PhpOffice\PhpWord\Style\Numbering->setLevels(Array)
#5 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Style/AbstractStyle.php(181): PhpOffice\PhpWord\Style\AbstractStyle->setStyleValue('levels', Array)
#6 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Style.php(188): PhpOffice\PhpWord\Style\AbstractStyle->setStyleByArray(Array)
#7 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Style.php(85): PhpOffice\PhpWord\Style::setStyleValues('PHPWordList3', Object(PhpOffice\PhpWord\Style\Numbering), Array)
#8 [internal function]: PhpOffice\PhpWord\Style::addNumberingStyle('PHPWordList3', Array)
#9 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/PhpWord.php(151): forward_static_call_array(Array, Array)
#10 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Reader/Word2007/Numbering.php(86): PhpOffice\PhpWord\PhpWord->__call('addNumberingSty...', Array)
#11 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Reader/Word2007/Numbering.php(86): PhpOffice\PhpWord\PhpWord->addNumberingStyle('PHPWordList3', Array)
#12 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Reader/Word2007.php(94): PhpOffice\PhpWord\Reader\Word2007\Numbering->read(Object(PhpOffice\PhpWord\PhpWord))
#13 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/Reader/Word2007.php(69): PhpOffice\PhpWord\Reader\Word2007->readPart(Object(PhpOffice\PhpWord\PhpWord), Array, 'Numbering', '/home/testproject/...', 'word/numbering....')
#14 /home/testproject/public_html/vendor/phpoffice/phpword/src/PhpWord/IOFactory.php(92): PhpOffice\PhpWord\Reader\Word2007->load('/home/testproject/...')
#15 /home/testproject/public_html/components/General.php(295): PhpOffice\PhpWord\IOFactory::load('/home/testproject/...')
#16 /home/testproject/public_html/commands/FilesController.php(75): app\components\General::GetDocxContent('/home/testproject/...')
#17 [internal function]: app\commands\FilesController->actionGetDocxContent()
#18 /home/testproject/public_html/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#19 /home/testproject/public_html/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#20 /home/testproject/public_html/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('get-docx-conten...', Array)
#21 /home/testproject/public_html/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('get-docx-conten...', Array)
#22 /home/testproject/public_html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('files/get-docx-...', Array)
#23 /home/testproject/public_html/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('files/get-docx-...', Array)
#24 /home/testproject/public_html/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#25 /home/testproject/public_html/yii(20): yii\base\Application->run()
#26 {main}
```

[i have error in this docx file](https://github.com/PHPOffice/PHPWord/files/1217090/7000.oloomejtemaei-00000488.docx)

**Comment by troosan** [comment]
that's because initially only bullet,decimal,upperRoman,lowerRoman,upperLetter,lowerLetter were accepted values for the formatting of the NumberingLevel.

If you try out the latest development version it should work as we now support all possible values defined in https://github.com/PHPOffice/PHPWord/blob/develop/src/PhpWord/SimpleType/NumberFormat.php

**Comment by troosan** [comment]
fixed by #1092

**Comment by Global90** [comment]
i use last version **0.13.0**

but i have this problem.

i add this file: https://github.com/PHPOffice/PHPWord/blob/develop/src/PhpWord/SimpleType/NumberFormat.php manualy?

**Comment by troosan** [comment]
No, that won't be enough. You need to use the development branch, or wait for 0.14.0
