### ISSUE TITLE
PhpOffice\PhpWord\Exception\InvalidImageException

### ISSUE THREAD

**Issue by iamsayantan** [PHPOffice/PHPWord#1223]
I am getting the above exception when I try to add image to word document. 
```
$phpWord = new \PhpOffice\PhpWord\PhpWord();
$style = [
    'height' => 104,
    'width' => 190,
    'marginLeft' => -2500
];

$section = $phpWord->addSection();
$src = base_url() . "/public/images/logo.jpg";

$headerTable = $section->addTable();
$headerTable->addRow();
$headerTable->addCell(5000)->addImage($src, $style);
```
This is the related code. And following is the stack trace,

```
#0 /home/sencillo/public_html/app/vendor/phpoffice/phpword/src/PhpWord/Element/Image.php(139): PhpOffice\PhpWord\Element\Image->checkImage('http://sencillo...')
#1 [internal function]: PhpOffice\PhpWord\Element\Image->__construct('http://sencillo...', Array)
#2 /home/sencillo/public_html/app/vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php(145): ReflectionClass->newInstanceArgs(Array)
#3 [internal function]: PhpOffice\PhpWord\Element\AbstractContainer->addElement('Image', 'http://sencillo...', Array)
#4 /home/sencillo/public_html/app/vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php(112): call_user_func_array(Array, Array)
#5 /home/sencillo/public_html/app/application/views/quotations-docx.php(41): PhpOffice\PhpWord\Element\AbstractContainer->__call('addImage', Array)
#6 /home/sencillo/public_html/app/application/views/quotations-docx.php(41): PhpOffice\PhpWord\Element\Cell->addImage('http://sencillo...', Array)
#7 /home/sencillo/public_html/app/system/core/Loader.php(962): include('/home/sencillo/...')
#8 /home/sencillo/public_html/app/system/core/Loader.php(489): CI_Loader->_ci_load(Array)
#9 /home/sencillo/public_html/app/application/controllers/Reports.php(153): CI_Loader->view('quotations-docx', Array, true)
#10 [internal function]: Reports->quotation('122')
#11 /home/sencillo/public_html/app/system/core/CodeIgniter.php(537): call_user_func_array(Array, Array)
#12 /home/sencillo/public_html/app/index.php(330): require_once('/home/sencillo/...')
#13 {main}
```

I was checking  the code for `checkImage` 
```
// Check image data
        if ($this->sourceType == self::SOURCE_ARCHIVE) {
            $imageData = $this->getArchiveImageSize($source);
        } else {
            $imageData = @getimagesize($source);
        }
``` 
Here `getimagesize($source)` is returning false.  But `$source` is valid and I have checked with the following snippet which is working fine,

```
<?php
$file = "http://example.com/public/images/logo.jpg"; // this is the value of $source
$info = getimagesize($file);

echo "<pre>" . print_r($info, true) . "</pre>";

?>
```
## Context

* PHP version 5.6.32
* PHPWord version: 0.13.0

**Comment by FBnil** [comment]
Running your test php script is from your user, but your website is running as apache or nobody, and thus it could be you do not have permissions to access that file under that apache user.
Try removing the `@` in @getimagesize (if it actually fails there, it will throw an error that could be useful) or check if the file is readable first: `is_readable($filename )`.

If you have SELinux, you also need to check for file context (ls -lZ) and maybe explicitely set the context `chcon -Rv --type=httpd_sys_content_t $imagefile` 

but maybe the basic permissions are not set:

chgrp -R www public/images && chmod -R g+w public/images (and check that apache is in the www group; and maybe you need to create that www group first)

**Comment by iamsayantan** [comment]
Thanks for the reply. In my case the `$src` is actually the url of the image and not the file path. So there should not be any issues with permission. And even so the project is hosted on Cpanel and there isn't much I can do about file permissions.

**Comment by troosan** [comment]
@iamsayantan do you have the same with version dev-develop?

**Comment by ahmed-bhs** [comment]
same issue here !
