### ISSUE TITLE
DOMElement::getAttribute() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by ikraddy** [PHPOffice/PHPWord#1369]
This is:

- [x] a bug report
- [ ] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpword)

I don't know how to read the docx file. I tried to read a docx file that I created, but I made a mistake.

How can I read the text and picture information in the docx file correctly?

```php
<?php
$filename = 'D:\projects/web/mydoc.docx';
$fh = IOFactory::load($filename);
```

### Context

* PHP version: 7.1.13
* PHPWord version: 0.14

```
Error:
Warning: DOMElement::getAttribute() expects parameter 1 to be string, array given in D:\projects\www\test\phpword\vendor\phpoffice\common\src\Common\XMLReader.php on line 140

Fatal error: Uncaught InvalidArgumentException: is not a valid value for PhpOffice\PhpWord\SimpleType\DocProtect, possible values are none, readOnly, comments, trackedChanges, forms in D:\projects\www\test\phpword\src\PhpWord\Shared\AbstractEnum.php:72 Stack trace: 
#0 D:\projects\www\test\phpword\src\PhpWord\Metadata\Protection.php(97): PhpOffice\PhpWord\Shared\AbstractEnum::validate(NULL) 
#1 D:\projects\www\test\phpword\src\PhpWord\Reader\Word2007\Settings.php(112): PhpOffice\PhpWord\Metadata\Protection->setEditing(NULL) 
#2 D:\projects\www\test\phpword\src\PhpWord\Reader\Word2007\Settings.php(71): PhpOffice\PhpWord\Reader\Word2007\Settings->setDocumentProtection(Object(PhpOffice\Common\XMLReader), Object(PhpOffice\PhpWord\PhpWord), Object(DOMElement)) 
#3 D:\projects\www\test\phpword\src\PhpWord\Reader\Word2007.php(94): PhpOffice\PhpWord\Reader\Word2007\Settings->read(Object(PhpOffice\PhpWord\PhpWord)) 
#4 D:\projects\www\test\phpword\src\PhpWord\Reader\Word2007.php(70): PhpOffice\PhpWord\Reader\Word2007->readPart(Object( in D:\projects\www\test\phpword\src\PhpWord\Shared\AbstractEnum.php on line 72
```

**Comment by troosan** [comment]
can you share the mydoc.docx (or any other document that generates this error)?

**Comment by ikraddy** [comment]
Thanks,This is a download link[https://pan.baidu.com/s/1yQBYqsy6ny87DiR68PIK5Q](url)

**Comment by troosan** [comment]
@ikraddy please try with the latest dev-develop version, it should be OK

**Comment by ikraddy** [comment]
Thank you very much. This time it will not be an error, but there are problems with the parsed content. The picture in my document seems to be unreadable. It is empty. I use a software called WPS from China.

**Comment by Kevin5211314** [comment]
哈哈，金山雄起！抓紧时间！China office

发自我的 iPhone
