### ISSUE TITLE
ZipArchive::close(): Failure to create temporary file: No such file or directory

### ISSUE THREAD

**Issue by ankit20893** [PHPOffice/PHPWord#1749]
***Please do not use the issue tracker to ask how to use PHPWord.***
ZipArchive::close(): Failure to create temporary file: No such file or directory

**Comment by llxx-lord-xxll** [comment]
Same issue here with Ubuntu. Worked fine in windows.

**Comment by Apteryks** [comment]
Perhaps a more descriptive error message could be printed?  Following the information in the backtrace:
```
16:41:09 Create new PhpWord object

Warning: ZipArchive::close(): Failure to create temporary file: No such file or directory in /var/www/html/vendor/phpoffice/phpword/src/PhpWord/Shared/ZipArchive.php on line 163

Fatal error: Uncaught PhpOffice\PhpWord\Exception\Exception: Could not close zip file /var/www/html/src/results/add-footer.docx:  in /var/www/html/vendor/phpoffice/phpword/src/PhpWord/Shared/ZipArchive.php:164
Stack trace:
#0 /var/www/html/vendor/phpoffice/phpword/src/PhpWord/Writer/Word2007.php(143): PhpOffice\PhpWord\Shared\ZipArchive->close()
#1 /var/www/html/vendor/phpoffice/phpword/src/PhpWord/PhpWord.php(373): PhpOffice\PhpWord\Writer\Word2007->save('/var/www/html/s...')
#2 /var/www/html/src/add-footer.php(28): PhpOffice\PhpWord\PhpWord->save('/var/www/html/s...', 'Word2007')
#3 /var/www/html/src/add-footer.php(93): write(Object(PhpOffice\PhpWord\PhpWord), 'add-footer', Array)
#4 {main}
  thrown in /var/www/html/vendor/phpoffice/phpword/src/PhpWord/Shared/ZipArchive.php on line 164
  ```
I started thinking there might be an issue with the PHP zip support in my environment.  A clear "Cannot save output file to non-existing directory: /var/www/html/src/results" or similar would probably have prevented that :-).
