### ISSUE TITLE
Error "Could not create a temporary file with unique name in the specified directory" of .docx file with images

### ISSUE THREAD

**Issue by Abelkrown** [PHPOffice/PHPWord#1819]
### Describe the Bug

When i try to load .docx file with image i get an exception 
`PHP Fatal error:  Uncaught exception 'PhpOffice\\PhpWord\\Exception\\CreateTemporaryFileException' with message 'Could not create a temporary file with unique name in the specified directory.' in .../vendor/phpoffice/phpword/src/PhpWord/Element/Image.php:485\nStack trace:\n#0 .../vendor/phpoffice/phpword/src/PhpWord/Element/Image.php(411): PhpOffice\\PhpWord\\Element\\Image->getArchiveImageSize('zip://testII.do...')\n#1 .../vendor/phpoffice/phpword/src/PhpWord/Element/Image.php(149): PhpOffice\\PhpWord\\Element\\Image->checkImage()\n#2 [internal function]: PhpOffice\\PhpWord\\Element\\Image->__construct('zip://testII.do...', NULL, false, NULL)\n#3 .../vendor/phpoffice/phpword/src/PhpWord/Element/AbstractContainer.php(145): ReflectionClass->newInstanceArgs(Array)\n#4 [internal function]: PhpOffice\\PhpWord\\Element\\AbstractContainer->addElement('Image', 'zip: in .../vendor/phpoffice/phpword/src/PhpWord/Element/Image.php on line 485`

In the same time if i delete all images from .docx file and try to load same .docx without images - all works perfectly.

### Steps to Reproduce

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$phpWord = IOFactory::load('test.docx');
```
Where 'test.docx' - file with images.

### Expected Behavior

The possibility to extract text from file (Don't care about images).

### Current Behavior

Unable to open file and get error "Could not create a temporary file with unique name in the specified directory."

### Context

- PHP Version: 7.0
- PHPWord Version: 0.17.0

**Comment by Niroj11** [comment]
I am also having an issue creating a docx file in the storage directory.

PHPWord: v0.17.*
LaravelL 5.8

**Comment by BlogAbout** [comment]
I am also having an issue "Could not create a temporary file with unique name in the specified directory."

The file *.doc with the image - successfully
The file *.docx without image - successfully
The file *.docx with the image - error

PHP version - 7.3
PHPWord version - 1.1.0

My stack trace:

`[
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Element\/Image.php",
        "line": 435,
        "function": "getArchiveImageSize",
        "class": "PhpOffice\\PhpWord\\Element\\Image",
        "type": "->",
        "args": [
            "\/home\/sites\/tmp\/phps0fy28#word\/media\/image1.png"
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Element\/Image.php",
        "line": 156,
        "function": "checkImage",
        "class": "PhpOffice\\PhpWord\\Element\\Image",
        "type": "->",
        "args": []
    },
    {
        "function": "__construct",
        "class": "PhpOffice\\PhpWord\\Element\\Image",
        "type": "->",
        "args": [
            "zip:\/\/\/home\/sites\/tmp\/phps0fy28#word\/media\/image1.png",
            null,
            false,
            null
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Element\/AbstractContainer.php",
        "line": 150,
        "function": "newInstanceArgs",
        "class": "ReflectionClass",
        "type": "->",
        "args": [
            [
                "zip:\/\/\/home\/sites\/tmp\/phps0fy28#word\/media\/image1.png",
                null,
                false,
                null
            ]
        ]
    },
    {
        "function": "addElement",
        "class": "PhpOffice\\PhpWord\\Element\\AbstractContainer",
        "type": "->",
        "args": [
            "Image",
            "zip:\/\/\/home\/sites\/tmp\/phps0fy28#word\/media\/image1.png",
            null,
            false,
            null
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Element\/AbstractContainer.php",
        "line": 116,
        "function": "call_user_func_array",
        "args": [
            [
                {},
                "addElement"
            ],
            [
                "Image",
                "zip:\/\/\/home\/sites\/tmp\/phps0fy28#word\/media\/image1.png",
                null,
                false,
                null
            ]
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Reader\/Word2007\/AbstractPart.php",
        "line": 276,
        "function": "__call",
        "class": "PhpOffice\\PhpWord\\Element\\AbstractContainer",
        "type": "->",
        "args": [
            "addimage",
            [
                "Image",
                "zip:\/\/\/home\/sites\/tmp\/phps0fy28#word\/media\/image1.png",
                null,
                false,
                null
            ]
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Reader\/Word2007\/AbstractPart.php",
        "line": 223,
        "function": "readRunChild",
        "class": "PhpOffice\\PhpWord\\Reader\\Word2007\\AbstractPart",
        "type": "->",
        "args": [
            {},
            {},
            {},
            "document",
            {
                "spaceAfter": "0"
            },
            []
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Reader\/Word2007\/AbstractPart.php",
        "line": 173,
        "function": "readRun",
        "class": "PhpOffice\\PhpWord\\Reader\\Word2007\\AbstractPart",
        "type": "->",
        "args": [
            {},
            {},
            {},
            "document",
            {
                "spaceAfter": "0"
            }
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Reader\/Word2007\/Document.php",
        "line": 152,
        "function": "readParagraph",
        "class": "PhpOffice\\PhpWord\\Reader\\Word2007\\AbstractPart",
        "type": "->",
        "args": [
            {},
            {},
            {}
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Reader\/Word2007\/Document.php",
        "line": 57,
        "function": "readWPNode",
        "class": "PhpOffice\\PhpWord\\Reader\\Word2007\\Document",
        "type": "->",
        "args": [
            {},
            {},
            {}
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Reader\/Word2007.php",
        "line": 98,
        "function": "read",
        "class": "PhpOffice\\PhpWord\\Reader\\Word2007\\Document",
        "type": "->",
        "args": [
            {}
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/Reader\/Word2007.php",
        "line": 75,
        "function": "readPart",
        "class": "PhpOffice\\PhpWord\\Reader\\Word2007",
        "type": "->",
        "args": [
            {},
            {
                "main": {
                    "rId1": {
                        "type": "officeDocument",
                        "target": "word\/document.xml",
                        "docPart": "word\/document",
                        "targetMode": null
                    },
                    "rId2": {
                        "type": "core-properties",
                        "target": "docProps\/core.xml",
                        "docPart": "docProps\/core",
                        "targetMode": null
                    },
                    "rId3": {
                        "type": "extended-properties",
                        "target": "docProps\/app.xml",
                        "docPart": "docProps\/app",
                        "targetMode": null
                    }
                },
                "document": {
                    "rId1": {
                        "type": "numbering",
                        "target": "word\/numbering.xml",
                        "docPart": "numbering",
                        "targetMode": null
                    },
                    "rId2": {
                        "type": "styles",
                        "target": "word\/styles.xml",
                        "docPart": "styles",
                        "targetMode": null
                    },
                    "rId3": {
                        "type": "settings",
                        "target": "word\/settings.xml",
                        "docPart": "settings",
                        "targetMode": null
                    },
                    "rId4": {
                        "type": "webSettings",
                        "target": "word\/webSettings.xml",
                        "docPart": "webSettings",
                        "targetMode": null
                    },
                    "rId5": {
                        "type": "footnotes",
                        "target": "word\/footnotes.xml",
                        "docPart": "footnotes",
                        "targetMode": null
                    },
                    "rId6": {
                        "type": "endnotes",
                        "target": "word\/endnotes.xml",
                        "docPart": "endnotes",
                        "targetMode": null
                    },
                    "rId7": {
                        "type": "image",
                        "target": "word\/media\/image1.png",
                        "docPart": "media\/image1.png",
                        "targetMode": null
                    },
                    "rId8": {
                        "type": "fontTable",
                        "target": "word\/fontTable.xml",
                        "docPart": "fontTable",
                        "targetMode": null
                    },
                    "rId9": {
                        "type": "theme",
                        "target": "word\/theme\/theme1.xml",
                        "docPart": "theme\/theme1",
                        "targetMode": null
                    }
                }
            },
            "Document",
            "\/home\/sites\/tmp\/phps0fy28",
            "word\/document.xml"
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/vendor\/phpoffice\/phpword\/src\/PhpWord\/IOFactory.php",
        "line": 89,
        "function": "load",
        "class": "PhpOffice\\PhpWord\\Reader\\Word2007",
        "type": "->",
        "args": [
            "\/home\/sites\/tmp\/phps0fy28"
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/core\/modules\/MSP\/Word\/Word.php",
        "line": 289,
        "function": "load",
        "class": "PhpOffice\\PhpWord\\IOFactory",
        "type": "::",
        "args": [
            "\/home\/sites\/tmp\/phps0fy28"
        ]
    },
    {
        "file": "\/home\/sites\/mysite\/public_html\/core\/modules\/main\/classes\/files.php",
        "line": 98,
        "function": "getContentWord",
        "class": "MSP\\Word\\Word",
        "type": "::",
        "args": [
            "\/home\/sites\/tmp\/phps0fy28",
            true
        ]
    },
    {
        ***
    },
]`
