### ISSUE TITLE
Uncaught ValueError: Invalid or uninitialized Zip object

### ISSUE THREAD

**Issue by Piermatte0** [PHPOffice/PHPWord#2605]
Hello, i've got this problem when i want to convert a doc file in pdf.
Fatal error: Uncaught ValueError: Invalid or uninitialized Zip object in C:\xampp\htdocs\test\assets\libs\phpoffice\vendor\phpoffice\phpword\src\PhpWord\Shared\XMLReader.php:65 Stack trace: #0 C:\xampp\htdocs\test\assets\libs\phpoffice\vendor\phpoffice\phpword\src\PhpWord\Shared\XMLReader.php(65): ZipArchive->getFromName('_rels/.rels') #1 C:\xampp\htdocs\test\assets\libs\phpoffice\vendor\phpoffice\phpword\src\PhpWord\Reader\Word2007.php(168): PhpOffice\PhpWord\Shared\XMLReader->getDomFromZip('ommit', '_rels/.rels') #2 C:\xampp\htdocs\test\assets\libs\phpoffice\vendor\phpoffice\phpword\src\PhpWord\Reader\Word2007.php(132): PhpOffice\PhpWord\Reader\Word2007->getRels('ommit', '_rels/.rels') #3 C:\xampp\htdocs\test\assets\libs\phpoffice\vendor\phpoffice\phpword\src\PhpWord\Reader\Word2007.php(47): PhpOffice\PhpWord\Reader\Word2007->readRelationships('omit') #4 C:\xampp\htdocs\test\assets\libs\phpoffice\vendor\phpoffice\phpword\src\PhpWord\IOFactory.php(89): PhpOffice\PhpWord\Reader\Word2007->load('') #5 C:\xampp\htdocs\test\doc.php(11): PhpOffice\PhpWord\IOFactory::load('omit') #6 {main} thrown in C:\xampp\htdocs\test\assets\libs\phpoffice\vendor\phpoffice\phpword\src\PhpWord\Shared\XMLReader.php on line 65

**Comment by Piermatte0** [comment]
<?php

require_once '../test/assets/libs/phpoffice/vendor/autoload.php'; 
$currentDirectory = __DIR__;
echo $currentDirectory;

$phpWord = new \PhpOffice\PhpWord\PhpWord();

$path = 'omit';
$docFile = $path . 'CL_12486.doc'; 
$doc = \PhpOffice\PhpWord\IOFactory::load($docFile);

$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($doc, 'PDF');

$pdfFile = 'document.pdf';
$objWriter->save($pdfFile);


?>
