### ISSUE TITLE
Saving to pdf error

### ISSUE THREAD

**Issue by ghost** [PHPOffice/PHPWord#407]
Hi,
I'm creating a docx successfully.
However right after generating it I cannot create a pdf version with TCPDF.

Here's my code:

```
$finalname = 'test'.uniqid(true);
$finalnamedocx = $finalname.'.docx';

/////////////////// SAVE AS DOCX ////////////////////
$objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($PHPWord, 'Word2007');
$objWriter->save($finalnamedocx); // so far so good

/////////////////// SAVE AS PDF ////////////////////
\PhpOffice\PhpWord\Settings::setPdfRendererPath('tcpdf_min'); // that's where it is
\PhpOffice\PhpWord\Settings::setPdfRendererName('TCPDF');
// reload it
$PHPWord = \PhpOffice\PhpWord\IOFactory::load($finalnamedocx);
$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($PHPWord , 'PDF');
$xmlWriter->save($finalname.'.pdf');
```

And here's my error stack:

```
PHP Fatal error:  Uncaught exception 'PhpOffice\PhpWord\Exception\InvalidImageException' in /home/hello/public_html/world/PHPWord-master/src/PhpWord/Element/Image.php:371
Stack trace:
#0 /home/hello/public_html/world/PHPWord-master/src/PhpWord/Element/Image.php(129): PhpOffice\PhpWord\Element\Image->checkImage('zip://test1...')
#1 [internal function]: PhpOffice\PhpWord\Element\Image->__construct('zip://test1...')
#2 /home/hello/public_html/world/PHPWord-master/src/PhpWord/Element/AbstractContainer.php(138): ReflectionClass->newInstanceArgs(Array)
#3 [internal function]: PhpOffice\PhpWord\Element\AbstractContainer->addElement('Image', 'zip://test1...')
#4 /home/hello/public_html/world/PHPWord-master/src/PhpWord/Element/AbstractContainer.php(101): call_user_func_array(Array, Array)
#5 /home/hello/public_html/world/PHPWord-master/src/PhpWord/Reader/Word2007/AbstractPart.php(222): PhpOffice\PhpWord\Element\AbstractContainer->__call('addImage', Array)
#6 /home/hello/public_html/worl in /home/hello/public_html/world/PHPWord-master/src/PhpWord/Element/Image.php on line 371
```

It looks like it's trying to access images at zip://filename??

**Comment by emepetres** [comment]
Hi guys, I'm having exactly the same problem as underfrog. The PHP version I'm using is 5.6.8 and I tried with both master and develop branches of DomPDF and PHPWord, without any luck.

Anyone has resolved this before?

**Comment by underfrog** [comment]
Hi emepetres,
My advice would be forget it. I know it sounds negative but it is simply not doable with this library.
4 months ago I spent days trying, and got several other highly skilled developers on the case, none succeeded. I ended up re-building my word document in tcpdf, which is a lot of work for a result that's not optimal since it's very hard to get the same result (different functionalities).

**Comment by emepetres** [comment]
Hi underfrog, 
I was hoping your advice could not be the most reasonable way to overcome this issue, but after trying all day long I have to agree with you lol. 

I'm thinking I'm going to give a try to html2pdf and see what it can do. Thank you for your answer.

**Comment by rajeshbabu54** [comment]
Hello everyone,
I want to add some images and text to existing docx in phpword.I tried with the following code but it is not showing correct.

include_once 'Sample_Header.php';
// New Word document
$name = basename(FILE, '.php');
$source = DIR . "/resources/{$name}.docx";
//$phpWord = new \PhpOffice\PhpWord\PhpWord();
$phpWord1 = \PhpOffice\PhpWord\IOFactory::load($source);
$document = $phpWord1->loadTemplate($source);
$document->saveAs('temp.docx');
$phpWord = \PhpOffice\PhpWord\IOFactory::load('temp.docx'); 
$section = $phpWord->addSection();
$section->addText(htmlspecialchars('Local image without any styles:'));
$section->addImage('resources/_mars.jpg');
$section->addTextBreak(2);
$source = 'http://php.net/images/logos/php-med-trans-light.gif';
$section->addText(htmlspecialchars("Remote image from: {$source}"));
$section->addImage($source);
$xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord , 'Word2007');
$xmlWriter->save('result1234566.docx');

Please send me the code. Please help me out from this problem

Thank you

Rajesh babu

**Comment by yjrowe** [comment]
public function office_to_pdf($FilePath, $FilePathPdf)
    {
        $rendererLibraryPath = ROOT_PATH . 'vendor/phpoffice/phpword/src/PhpWord/Writer/PDF';
        \PhpOffice\PhpWord\Settings::setPdfRendererPath($rendererLibraryPath);
        \PhpOffice\PhpWord\Settings::setPdfRendererName('DomPDF');

        //Load temp file
        $phpWord = \PhpOffice\PhpWord\IOFactory::load($FilePath);

        //Save it
        $xmlWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord , 'PDF');
        $xmlWriter->save($FilePathPdf);
    }

the pdf is not same as docx and chartset is wrong, how to solve this problem? thanks in advance.

**Comment by microjafar** [comment]
(new \PhpOffice\PhpWord\Writer\PDF\DomPDF($phpWord))->save'helloWorld.pdf');
