### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by clarkk** [PHPOffice/PHPWord#509]
http://www.filedropper.com/test_37

require_once Ini::get('path/class').'/third-party/phpword/Autoloader.php';
PhpOffice\PhpWord\Autoloader::register();
PhpOffice\PhpWord\Settings::setPdfRendererPath(Ini::get('path/class').'/third-party/tcpdf');
PhpOffice\PhpWord\Settings::setPdfRendererName('TCPDF');
$word = PhpOffice\PhpWord\IOFactory::load('/root/test.docx');
$writer = PhpOffice\PhpWord\IOFactory::createWriter($word, 'PDF');
$writer->save('/root/output.pdf');

PHP Fatal error:  Uncaught exception 'PhpOffice\PhpWord\Exception\Exception' with message 'Cannot find archive file.' in /var/www/class/third-party/phpword/Shared/XMLReader.php:54
Stack trace:
#0 /var/www/class/third-party/phpword/Reader/Word2007.php(144): PhpOffice\PhpWord\Shared\XMLReader->getDomFromZip('/root/test.docx', '_rels/.rels')
#1 /var/www/class/third-party/phpword/Reader/Word2007.php(109): PhpOffice\PhpWord\Reader\Word2007->getRels('/root/test.docx', '_rels/.rels')
#2 /var/www/class/third-party/phpword/Reader/Word2007.php(42): PhpOffice\PhpWord\Reader\Word2007->readRelationships('/root/test.docx')
#3 /var/www/class/third-party/phpword/IOFactory.php(73): PhpOffice\PhpWord\Reader\Word2007->load('/root/test.docx')
#4 /var/www/class/Cronjob_test.php(28): PhpOffice\PhpWord\IOFactory::load('/root/test.docx')
#5 /var/www/class/Cronjob_test.php(9): Cronjob_test->convert_docx()
#6 /var/www/class/Cronjob.php(75): Cronjob_test->__construct in /var/www/class/third-party/phpword/Shared/XMLReader.php on line 54

Fatal error: Uncaught exception 'PhpOffice\PhpWord\Exception\Exception' with message 'Cannot find archive file.' in /var/www/class/third-party/phpword/Shared/XMLReader.php:54
Stack trace:
#0 /var/www/class/third-party/phpword/Reader/Word2007.php(144): PhpOffice\PhpWord\Shared\XMLReader->getDomFromZip('/root/test.docx', '_rels/.rels')
#1 /var/www/class/third-party/phpword/Reader/Word2007.php(109): PhpOffice\PhpWord\Reader\Word2007->getRels('/root/test.docx', '_rels/.rels')
#2 /var/www/class/third-party/phpword/Reader/Word2007.php(42): PhpOffice\PhpWord\Reader\Word2007->readRelationships('/root/test.docx')
#3 /var/www/class/third-party/phpword/IOFactory.php(73): PhpOffice\PhpWord\Reader\Word2007->load('/root/test.docx')
#4 /var/www/class/Cronjob_test.php(28): PhpOffice\PhpWord\IOFactory::load('/root/test.docx')
#5 /var/www/class/Cronjob_test.php(9): Cronjob_test->convert_docx()
#6 /var/www/class/Cronjob.php(75): Cronjob_test->__construct in /var/www/class/third-party/phpword/Shared/XMLReader.php on line 54

**Comment by marie1st** [comment]
The possibilities of error is 2 alternatives: 
1. folder permission, try chmod 777 [folder_name]
2. at PhpOffice\PhpWord\IOFactory::load('relative_path_to_root_directory');
