### ISSUE TITLE
Error loading ZipArchive class with php 7.0

### ISSUE THREAD

**Issue by taophp** [PHPOffice/PHPWord#888]
I got an error related with class autoloading when loading a document with php 7.0:
```php
$ php7.0 -f index.php 
PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /var/www/projects/LinuxMag/phpword/vendor/phpoffice/common/src/Common/XMLReader.php:54
Stack trace:
#0 /var/www/projects/LinuxMag/phpword/vendor/phpoffice/phpword/src/PhpWord/Reader/Word2007.php(145): PhpOffice\Common\XMLReader->getDomFromZip('/var/www/projec...', '_rels/.rels')
#1 /var/www/projects/LinuxMag/phpword/vendor/phpoffice/phpword/src/PhpWord/Reader/Word2007.php(110): PhpOffice\PhpWord\Reader\Word2007->getRels('/var/www/projec...', '_rels/.rels')
#2 /var/www/projects/LinuxMag/phpword/vendor/phpoffice/phpword/src/PhpWord/Reader/Word2007.php(42): PhpOffice\PhpWord\Reader\Word2007->readRelationships('/var/www/projec...')
#3 /var/www/projects/LinuxMag/phpword/vendor/phpoffice/phpword/src/PhpWord/IOFactory.php(92): PhpOffice\PhpWord\Reader\Word2007->load('/var/www/projec...')
#4 /var/www/projects/LinuxMag/phpword/index.php(6): PhpOffice\PhpWord\IOFactory::load('/var/www/projec...')
#5 {main}
  thrown in /var/www/projects/LinuxMag/phpword/vendor/phpoffice/common/src/Common/XMLReader.php on line 54
```
Curiously, no problem with PHP 5.6.

The php source:
```php
<?php
$source = __DIR__."/mon_model-LP.docx";

require __DIR__ . '/vendor/autoload.php';
$phpWord = \PhpOffice\PhpWord\IOFactory::load($source);
```

**Comment by gplaza** [comment]
Not a bug, you need to install the extension zip from php :
apt-get install php7.0-zip

Cheer.

**Comment by taophp** [comment]
Oh. Sorry. Thanks.

**Comment by slugaboga** [comment]
Огромное спасибо!
Тоже помогло!
Ребята вы лучшие!
